before:
  hooks:
    - go mod download

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

builds:
  - id: bionic_darwin
    binary: bionic
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -tags
      - sqlite

  - id: bionic_linux
    binary: bionic
    env:
      - CGO_ENABLED=1
    flags:
      - -tags
      - sqlite
    goos:
      - linux
    goarch:
      - amd64
      - 386

  - id: bionic_windows_i686
    binary: bionic
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    flags:
      - -tags
      - sqlite
    goos:
      - windows
    goarch:
      - 386

  - id: bionic_windows_x64
    binary: bionic
    ldflags:
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -tags
      - sqlite
    goos:
      - windows
    goarch:
      - amd64

brews:
  - tap:
      owner: bionic-dev
      name: homebrew-bionic
      token: "{{ .Env.API_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/bionic-dev/bionic
